CREATE TABLE CANDIDATE(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	CANDIDATE_NAME VARCHAR(2000),
	CANDIDATE_SURNAME VARCHAR(2000),
	CANDIDATE_CATEGORY VARCHAR(2000)
);
